# Generated by Django 5.0 on 2023-12-15 04:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductosEgreso',
            new_name='EgressProduc',
        ),
    ]
