# Generated by Django 5.0 on 2023-12-15 04:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
        ('sales', '0002_rename_productosegreso_egressproduc'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EgressProduc',
            new_name='EgressProduct',
        ),
    ]
